### ISSUE TITLE
Requires PIL after all?

### ISSUE THREAD

**Issue by jonnyijapan** [bernii/PyQRNativeGAE#1]
I get this from your sample code:

File "/base/data/home/apps/s~appname/1.384434024790381092/PyQRNative.py", line 2, in <module>
    from PIL import Image, ImageDraw
ImportError: No module named PIL

**Comment by ZMYaro** [comment]
@jonnyijapan: You can include `PIL` in your App Engine app by adding it to the `libraries:` section of your `app.yaml`:
```
libraries:
- name: PIL
  version: latest
```
